### ISSUE TITLE
plotting

### ISSUE THREAD

**Issue by nilsbecker** [pveber/ocaml-r#11]
some more testing ;)

```
module St = OCamlR_stats ;;
let rans = St.rnorm 1232;;
OCamlR_graphics.hist rans;;
2018-11-21 13:49:34.982 ocamlrun[12873:5334759] Metal pipeline state creation failed with error: Error Domain=MTLLibraryErrorDomain Code=3 "Compiler encountered an internal error" UserInfo={NSLocalizedDescription=Compiler encountered an internal error}
Out[27]:
- : OCamlR_graphics.hist = <obj>
```
At this point an XQuartz window is open but is filled with a lot of numbers rendered as text (i assume the actual random values)
then, 
```
module G = OCamlR_graphics;;
G.plot ~plot_type:`Lines ~x:[|11.;21.|] ~y:[|3.;3.2|] ~main:"sdf" ();;
```
works, but updates the graphics window only on a second invocation of the plot command. maybe connected to this, i get a pinwheel when i mouse over the graphics window. it never gets focus -- i cannot invoke any window menu items on it either.

i cannot seem to get hist to render correctly -- i always get the histogram overlayed with the raw data rendered as text.
<img width="799" alt="image" src="https://user-images.githubusercontent.com/177614/48843333-0c7a8200-ed97-11e8-91c1-315c31a6c6bf.png">

**Comment by pveber** [comment]
Yes, you should provide a value for `xlab` and  `main` arguments, otherwise R tries to build one and it destroys the plot. I've changed the default values to avoid this problem, you can try the change by pinning the repo.
