### ISSUE TITLE
Jumping between REPLs

### ISSUE THREAD

**Issue by drjdn** [pveber/ocaml-r#16]
I've become used to jumping between REPL's like [reticulate](https://rstudio.github.io/reticulate/index.html) in R for python and [RCall](https://github.com/JuliaInterop/RCall.jl) for julia.  Pretty sure this isn't currently possible with OCaml-R but I'm wondering if you have any ideas/hints of what it would take to make that a reality.

**Comment by pveber** [comment]
Sorry for not replying earlier. I guess most of the work would have to be done in the REPL itself (ocaml or utop). OCaml-R provides an `eval_string` function and print functions, so I guess everything's here already.

**Comment by pveber** [comment]
closing for now, feel free to reopen if useful
