### ISSUE TITLE
Package libRmath was not found in the pkg-config search path. Perhaps you should add the directory containing `libRmath.pc'

### ISSUE THREAD

**Issue by UnixJunkie** [pveber/ocaml-r#5]
Hello, I think some depexts are missing in the opam file.
Or a conf-r package should be added to opam.
Do you know which packages are necessary on Debian/Ubuntu so that it compiles?
regards,
F.

**Comment by UnixJunkie** [comment]
r-mathlib is required probably

**Comment by UnixJunkie** [comment]
related to https://github.com/pveber/OCaml-R/pull/6

**Comment by UnixJunkie** [comment]
if you add the package to opam, that would be nice

**Comment by pveber** [comment]
Is it working with the debian package?

As for releasing, as explained in your other issue, I'm afraid there is still some work needed. In the mean time (and thanks to your contribution), it should be easy enough to pin the git repo.

**Comment by UnixJunkie** [comment]
On 2017/09/02 7:40, pveber wrote:
> Is it working with the debian package?
>
> As for releasing, as explained in your other issue, I'm afraid there is
> still some work needed. In the mean time (and thanks to your
> contribution), it should be easy enough to pin the git repo.

If it can be opam pinned, then I think it means it is good enough
to do a 1.0.0 release in opam.
